/*
SG340024_GetBasket.sql
<Process>
	<Execution>
        <Commander Timeout = "600" />
    </Execution>
</Process>  

*/

DECLARE @PROCESS_DATE NUMERIC(10,0)
SET @PROCESS_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(), 112));

SELECT
	AVL.HKAVL_DATE, 	
	RIC.INSALA_INSTR_INSNBR,
	BMBG.INSALA_CODE,	
	ISNULL(AVL.HKAVL_MARGIN_AC_BALANCE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 0) AS USD_TOTAL_SIZE,
	ISNULL(AVL.HKAVL_SHORT_SELLING_AC_BALANCE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 0) AS USD_SBL_LENT,
	ISNULL(AVL.HKAVL_SBL_AVAILABLE_BALANCE, 0) AS HKAVL_SBL_AVAILABLE_BALANCE,
	ISNULL(SBLRATE.HKDSR_SBL_RATE_1, 0) AS SBL_RATE,--30DAY
	ISNULL(AVL.HKAVL_NO_OF_MARGIN_HOLDER, 0) AS HKAVL_NO_OF_MARGIN_HOLDER,
	ISNULL(AVL.HKAVL_MARGIN_AC_BALANCE, 0) AS HKAVL_MARGIN_AC_BALANCE,
	ISNULL(AVL.HKAVL_SHORT_SELLING_AC_BALANCE, 0) AS HKAVL_SHORT_SELLING_AC_BALANCE,
	ISNULL(CASE
	       	  WHEN AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE < 0
	       	  THEN AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE
	       	  ELSE 0
	       END, 0)	AS SHORT_SELL
FROM EXTSRC.dbo.HK_SBL_AVAILABLE_GSPS AVL
LEFT JOIN WAFT.dbo.INS_ALIAS RIC
ON RIC.INSALA_TYPE = 'RIC'
AND RIC.INSALA_CODE = HKAVL_REUTER_CODE
LEFT JOIN WAFT.dbo.INS_ALIAS BMBG
ON BMBG.INSALA_TYPE = 'BMBG'
AND BMBG.INSALA_INSTR_INSNBR = RIC.INSALA_INSTR_INSNBR
LEFT JOIN WAFT.dbo.INS_INSTRUMENT INS
ON RIC.INSALA_INSTR_INSNBR=INS.INSTR_INSNBR
AND INS.INSTR_VER = 1
LEFT JOIN WARP.dbo.HISPRICE PX
ON PX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND PX.HISPRS_INSTR_INSNBR = RIC.INSALA_INSTR_INSNBR
AND PX.HISPRS_TYPE = 'CLOSE_MARKET'
LEFT JOIN WARP.dbo.HISPRICE EX
ON EX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND EX.HISPRS_INSTR_INSNBR = INS.INSTR_CURRENCY_INSNBR
AND EX.HISPRS_TYPE = 'CLOSE_MARKET'
AND EX.HISPRS_CURRENCY_INSNBR= 11--USD
LEFT JOIN EXTSRC.dbo.HK_SBL_DAILY_SBL_RATE SBLRATE
ON SBLRATE.HKDSR_TICKER + ' EQUITY' = BMBG.INSALA_CODE
AND HKDSR_DATE = @PROCESS_DATE
WHERE ISNULL(BMBG.INSALA_CODE, '') <> ''
AND HKAVL_DATE = @PROCESS_DATE
AND ('ALL' IN (@INSTR_INSNBR) OR REPLACE(BMBG.INSALA_CODE, ' EQUITY', '') IN (@INSTR_INSNBR))
ORDER BY ISNULL(CASE
	            	  WHEN AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE < 0
	            	  THEN AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE
	            	  ELSE 0
	            END, 0)