/*
SG340028_GetSBL.sql

*/

SELECT
  HKSBL_TRDNBR,
  HKSBL_DIRECTION,
  HKSBL_TRADE_DATE,
  HKSBL_VALUE_DATE,
  HKSBL_COUNTERPARTY,
  HKSBL_INSNBR,
  HKSBL_PRICE,
  HKSBL_DIVIDEND,
  HKSBL_QUANTITY,
  HKSBL_SBL_RATE
FROM WAFT.dbo.HK_SBL_SBL
WHERE HKSBL_TRDNBR = @HKSBL_TRDNBR
