/*
SG340028_CheckHoldQuantity.sql

*/

SELECT  
  HLD.HKOHD_QUANTITY - ISNULL(SBL.HKSBL_QUANTITY, 0) AS HKOHD_QUANTITY
FROM WAFT.dbo.HK_SBL_HOLD AS HLD
LEFT JOIN
(
    SELECT HKSBL_HOLD_SEQ, SUM(HKSBL_QUANTITY) AS HKSBL_QUANTITY
    FROM WAFT.dbo.HK_SBL_SBL
    GROUP BY HKSBL_HOLD_SEQ
) AS SBL
    ON HLD.HKOHD_ROWSEQ = SBL.HKSBL_HOLD_SEQ
WHERE HLD.HKOHD_ROWSEQ = @HKOHD_ROWSEQ

