/*
SG340024_GetDateDetail.sql

*/

DECLARE @PROCESS_DATE NUMERIC(10,0)
SET @PROCESS_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(), 112));

SELECT INSTR_INSNBR, HKBFW_HKSE_CODE, HKBFW_DATE1, HKBFW_DATE2, HKBFW_DATE3, HKBFW_DATE4, HKBFW_DATE5, HKBFW_DATE6
FROM (
SELECT 1 SEQ, HKBFW_GLOSS_INSTRUMENT_CODE, HKBFW_HKSE_CODE, HKBFW_DATE1, HKBFW_DATE2, HKBFW_DATE3, HKBFW_DATE4, HKBFW_DATE5, HKBFW_DATE6
FROM EXTSRC.dbo.HK_SBL_BALANCE_FIVE_WEEKS
WHERE HKBFW_DATE = @PROCESS_DATE
UNION ALL
SELECT 2 SEQ, HKBFW_GLOSS_INSTRUMENT_CODE, HKBFW_HKSE_CODE, HKBFW_QUANTITY1, HKBFW_QUANTITY2, HKBFW_QUANTITY3, HKBFW_QUANTITY4, HKBFW_QUANTITY5, HKBFW_QUANTITY6
FROM EXTSRC.dbo.HK_SBL_BALANCE_FIVE_WEEKS
WHERE HKBFW_DATE = @PROCESS_DATE
) A
INNER JOIN WAFT.dbo.INS_INSTRUMENT
ON INSTR_VER = 1
AND INSTR_ID = HKBFW_GLOSS_INSTRUMENT_CODE
AND INSTR_INSNBR = @INSTR_INSNBR--29647
ORDER BY SEQ