/*
SG340024_GetTickers.sql

*/

SELECT
    INS.INSTR_INSNBR,
    REPLACE(IAS.INSALA_CODE, ' EQUITY', '') + ' ' + INS.INSTR_NAME AS INSTR_CODE
FROM WAFT.dbo.INS_ALIAS AS IAS
JOIN WAFT.dbo.INS_INSTRUMENT AS INS
    ON IAS.INSALA_INSTR_INSNBR = INS.INSTR_INSNBR
    AND INS.INSTR_VER = 1
    AND INS.INSTR_MARKET_TYPE IN ('HK EQTY MKT', 'HK EQTY MKT1')
	AND INS.INSTR_STATUS = 'Active'
	AND INS.INSTR_TYPE = 'EQTY'
    AND UPPER(INS.INSTR_NAME) NOT LIKE '*I*%'
    AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DEL%'
    AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLIST%'
    AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLST%'
    AND UPPER(INS.INSTR_NAME) NOT LIKE '%(UNLIS%'
WHERE IAS.INSALA_TYPE = 'BMBG'
