/*
SG340024_GetInventory.sql

*/

DECLARE @PROCESS_DATE NUMERIC(10,0)
SET @PROCESS_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(), 112));

SELECT
	ALA.INSALA_CODE,
	INS.INSTR_NAME,
	ISNULL(PX.HISPRS_CLOSE, 0) AS HISPRS_CLOSE,
	ISNULL(ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 0) AS PX_IN_USD,
	CASE
		WHEN HSI.FLGDAT_FLGDTA IS NOT NULL THEN 'HSI INDEX'
		WHEN HSCEI.FLGDAT_FLGDTA IS NOT NULL THEN 'HSCEI INDEX'
		WHEN HSCI.FLGDAT_FLGDTA IS NOT NULL THEN 'HSCI INDEX'
		ELSE ''
	END [INDEX],
	ISNULL(BE.HKBE_EX_DIVIDEND_DATE, 0) AS HKBE_EX_DIVIDEND_DATE,
	ISNULL(LOTSIZE.FLGDAT_FLGNBR, 0) AS ROUND_LOT,
	ISNULL(SBLRATE.HKDSR_SBL_RATE_2, 0) AS [5_DAYS_FEE]
FROM WAFT.dbo.INS_ALIAS ALA
INNER JOIN WAFT.dbo.INS_INSTRUMENT INS
ON INS.INSTR_INSNBR = ALA.INSALA_INSTR_INSNBR
AND INS.INSTR_MARKET_TYPE IN ('HK EQTY MKT', 'HK EQTY MKT1')
AND INS.INSTR_VER = 1
AND INS.INSTR_TYPE = 'EQTY'
AND INS.INSTR_STATUS = 'Active'
AND UPPER(INS.INSTR_NAME) NOT LIKE '*I*%'
AND UPPER(INS.INSTR_NAME) NOT LIKE '"I"%'
AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DEL%'
AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLIST%'
AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLST%'
AND UPPER(INS.INSTR_NAME) NOT LIKE '%(UNLIS%'
LEFT JOIN WARP.dbo.HISPRICE PX
ON PX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND PX.HISPRS_INSTR_INSNBR = INS.INSTR_INSNBR
AND PX.HISPRS_TYPE = 'CLOSE_MARKET'
LEFT JOIN WARP.dbo.HISPRICE EX
ON EX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND EX.HISPRS_INSTR_INSNBR = INS.INSTR_CURRENCY_INSNBR
AND EX.HISPRS_TYPE = 'CLOSE_MARKET'
AND EX.HISPRS_CURRENCY_INSNBR= 11--USD
LEFT JOIN EDAISYS.dbo.FLAGDATAS HSI
ON HSI.FLGDAT_FLGNAM = 'HK_SBL_INDEX'
AND HSI.FLGDAT_FLGVAR = 'HSI INDEX'
AND HSI.FLGDAT_FLGDTA + ' EQUITY' = ALA.INSALA_CODE
LEFT JOIN EDAISYS.dbo.FLAGDATAS HSCEI
ON HSCEI.FLGDAT_FLGNAM = 'HK_SBL_INDEX'
AND HSCEI.FLGDAT_FLGVAR = 'HSCEI INDEX'
AND HSCEI.FLGDAT_FLGDTA + ' EQUITY' = ALA.INSALA_CODE
LEFT JOIN EDAISYS.dbo.FLAGDATAS HSCI
ON HSCI.FLGDAT_FLGNAM = 'HK_SBL_INDEX'
AND HSCI.FLGDAT_FLGVAR = 'HSCI INDEX'
AND HSCI.FLGDAT_FLGDTA + ' EQUITY' = ALA.INSALA_CODE
LEFT JOIN (
	SELECT HKBE_EX_DIVIDEND_DATE,HKBE_STOCK
	FROM (
		SELECT
		    ROW_NUMBER() OVER (PARTITION BY HKBE_STOCK ORDER BY HKBE_EX_DIVIDEND_DATE) AS SEQ,
		    HKBE_EX_DIVIDEND_DATE,HKBE_STOCK
		FROM EXTSRC.dbo.HK_BENEFIT_ENTITLEMENT
		WHERE HKBE_EX_DIVIDEND_DATE >= @PROCESS_DATE
		AND HKBE_EX_DIVIDEND_DATE <> 99991231) HKBE
	WHERE HKBE.SEQ = 1) BE
ON BE.HKBE_STOCK + ' HK EQUITY' = ALA.INSALA_CODE
LEFT JOIN EDAISYS.dbo.FLAGDATAS	LOTSIZE
ON LOTSIZE.FLGDAT_FLGNAM = 'SEHK_LOTSIZE'
AND LOTSIZE.FLGDAT_FLGVAR + ' HK EQUITY' = ALA.INSALA_CODE
LEFT JOIN EXTSRC.dbo.HK_SBL_DAILY_SBL_RATE SBLRATE
ON SBLRATE.HKDSR_TICKER + ' EQUITY' = ALA.INSALA_CODE
AND HKDSR_DATE = @PROCESS_DATE
WHERE ALA.INSALA_TYPE = 'BMBG'
AND INS.INSTR_INSNBR = @INSTR_INSNBR
