/*
SG340025_GetHold.sql

*/

SELECT
  HLD.HKOHD_ROWSEQ,
  HLD.HKOHD_DATE,
  HLD.HKOHD_TYPE,
  HLD.HKOHD_COUNTERPARTY,
  FLG.FLGDAT_FLGDTA,
  HLD.HKOHD_INSNBR,
  INS.INSTR_CODE,
  HLD.HKOHD_QUANTITY,
  HLD.HKOHD_SBL_RATE
FROM WAFT.dbo.HK_SBL_HOLD AS HLD
JOIN 
(
    SELECT
        INS.INSTR_INSNBR,
        REPLACE(IAS.INSALA_CODE, ' EQUITY', '') AS INSTR_CODE
    FROM WAFT.dbo.INS_ALIAS AS IAS
    JOIN WAFT.dbo.INS_INSTRUMENT AS INS
        ON IAS.INSALA_INSTR_INSNBR = INS.INSTR_INSNBR
        AND INS.INSTR_VER = 1
        AND INS.INSTR_MARKET_TYPE IN ('HK EQTY MKT', 'HK EQTY MKT1')
	    AND INS.INSTR_STATUS = 'Active'
	    AND INS.INSTR_TYPE = 'EQTY'
	    AND UPPER(INS.INSTR_NAME) NOT LIKE '*I*%'
        AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DEL%'
        AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLIST%'
        AND UPPER(INS.INSTR_NAME) NOT LIKE '%(DLST%'
        AND UPPER(INS.INSTR_NAME) NOT LIKE '%(UNLIS%'
    WHERE IAS.INSALA_TYPE = 'BMBG'
) AS INS
    ON HLD.HKOHD_INSNBR = INS.INSTR_INSNBR
JOIN EDAISYS.dbo.FLAGDATAS AS FLG
    ON HLD.HKOHD_COUNTERPARTY = FLG.FLGDAT_FLGVAR
    AND FLG.FLGDAT_FLGNAM = 'HK_SBL_COUNTERPARTY' 
LEFT JOIN
(
    SELECT HKSBL_HOLD_SEQ, SUM(HKSBL_QUANTITY) AS HKSBL_QUANTITY
    FROM WAFT.dbo.HK_SBL_SBL
    GROUP BY HKSBL_HOLD_SEQ
) AS SBL
    ON HLD.HKOHD_ROWSEQ = SBL.HKSBL_HOLD_SEQ
WHERE (HLD.HKOHD_DATE = @HKOHD_DATE OR @HKOHD_DATE = -1)
AND (HLD.HKOHD_INSNBR = @HKOHD_INSNBR OR @HKOHD_INSNBR = -1)
AND HLD.HKOHD_QUANTITY <> ISNULL(SBL.HKSBL_QUANTITY, 0)

