/*
SG340024_GetTradeDetail.sql

*/

DECLARE @PROCESS_DATE NUMERIC(10,0)
SET @PROCESS_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(), 112));

SELECT HKOPT_DATE, HKOPT_COUNTERPARTY, HKOPT_TRADE_TYPE, HKOPT_OPEN, HKOPT_TRADE_DATE, HKOPT_VALUE_DATE, HKOPT_START, HKOPT_END, HKOPT_QUANTITY, HKOPT_FEE
FROM EXTSRC.dbo.HK_SBL_FI_TRADE_DATA
INNER JOIN WAFT.dbo.INS_ALIAS BMBG
ON BMBG.INSALA_TYPE = 'BMBG'
AND BMBG.INSALA_CODE = HKOPT_UNDERLYING + ' EQUITY'
WHERE HKOPT_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND BMBG.INSALA_INSTR_INSNBR = @INSTR_INSNBR--29647
