/*
SG340027_GetSBLCSV.sql

*/

SELECT
  SBL.HKSBL_COUNTERPARTY,
  SBL.HKSBL_DIRECTION,
  INS.INSTR_CODE,
  CONVERT(VARCHAR(20), CAST(SBL.HKSBL_QUANTITY AS FLOAT)) + ' Shs' AS HKSBL_QUANTITY,
  CONVERT(VARCHAR(20), CAST(SBL.HKSBL_PRICE AS FLOAT)) + ' HKD' AS HKSBL_PRICE,
  CONVERT(VARCHAR(20), CAST(SBL.HKSBL_SBL_RATE AS FLOAT)) + '%' AS HKSBL_SBL_RATE,
  'vd ' + FORMAT(
    CONVERT(DATETIME, CONVERT(NVARCHAR, SBL.HKSBL_VALUE_DATE), 112),
    'dd-MMM',
    'en-US'
) AS HKSBL_VALUE_DATE
,
  CONVERT(VARCHAR(20), CAST(SBL.HKSBL_DIVIDEND AS FLOAT)) + '% Div' AS HKSBL_DIVIDEND
FROM WAFT.dbo.HK_SBL_SBL AS SBL
JOIN 
(
    SELECT
        INS.INSTR_INSNBR,
        REPLACE(IAS.INSALA_CODE, ' EQUITY', '') AS INSTR_CODE
    FROM WAFT.dbo.INS_ALIAS AS IAS
    JOIN WAFT.dbo.INS_INSTRUMENT AS INS
        ON IAS.INSALA_INSTR_INSNBR = INS.INSTR_INSNBR
        AND INS.INSTR_VER = 1
        AND INS.INSTR_MARKET_TYPE IN ('HK EQTY MKT', 'HK EQTY MKT1')
	    AND INS.INSTR_STATUS = 'Active'
	    AND INS.INSTR_TYPE = 'EQTY'
	    AND INS.INSTR_NAME NOT LIKE '*I*%'
    WHERE IAS.INSALA_TYPE = 'BMBG'
) AS INS
    ON SBL.HKSBL_INSNBR = INS.INSTR_INSNBR
JOIN EDAISYS.dbo.FLAGDATAS AS FLG
    ON SBL.HKSBL_COUNTERPARTY = FLG.FLGDAT_FLGVAR
    AND FLG.FLGDAT_FLGNAM = 'HK_SBL_COUNTERPARTY'
WHERE (SBL.HKSBL_TRADE_DATE = @HKSBL_TRADE_DATE OR @HKSBL_TRADE_DATE = -1)
AND (SBL.HKSBL_INSNBR = @HKSBL_INSNBR OR @HKSBL_INSNBR = -1)
