/*
SG340024_GetSBLDetail.sql

*/

DECLARE @PROCESS_DATE NUMERIC(10,0)
SET @PROCESS_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(), 112));
WITH POSITION AS (
SELECT
	HKAVL_DATE,
	RIC.INSALA_INSTR_INSNBR,
	BMBG.INSALA_CODE,
	AVL.HKAVL_MARGIN_AC_BALANCE,
	AVL.HKAVL_SHORT_SELLING_AC_BALANCE,
	AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE AS ACTUAL_AVAILABLE,
	AVL.HKAVL_NO_OF_MARGIN_HOLDER,
	ISNULL(SBL.SBL_TOTAL, 0) AS SBL_TOTAL,
	ISNULL(HOLD.HOLD_TOTAL, 0) AS HOLD_TOTAL,
	AVL.HKAVL_MARGIN_AC_BALANCE + AVL.HKAVL_SHORT_SELLING_AC_BALANCE + ISNULL(SBL.SBL_TOTAL, 0) - ISNULL(HOLD.HOLD_TOTAL, 0) AS REMAINING_BALANCE
FROM EXTSRC.dbo.HK_SBL_AVAILABLE_GSPS AVL
LEFT JOIN WAFT.dbo.INS_ALIAS RIC
ON RIC.INSALA_TYPE = 'RIC'
AND RIC.INSALA_CODE = HKAVL_REUTER_CODE
LEFT JOIN WAFT.dbo.INS_ALIAS BMBG
ON BMBG.INSALA_TYPE = 'BMBG'
AND BMBG.INSALA_INSTR_INSNBR = RIC.INSALA_INSTR_INSNBR
LEFT JOIN (
	SELECT HKSBL_TRADE_DATE, HKSBL_INSNBR, SUM(BORROW) - SUM(LEND) AS SBL_TOTAL
	FROM (
		SELECT
			HKSBL_TRADE_DATE, HKSBL_INSNBR, HKSBL_COUNTERPARTY, SUM(IIF(HKSBL_DIRECTION ='BORROW', HKSBL_QUANTITY,0)) AS BORROW, SUM(IIF(HKSBL_DIRECTION ='LEND', HKSBL_QUANTITY,0)) AS LEND
		FROM WAFT.dbo.HK_SBL_SBL
		WHERE HKSBL_TRADE_DATE = @PROCESS_DATE
		AND HKSBL_INSNBR = @INSTR_INSNBR
		AND HKSBL_VER = 1
		GROUP BY HKSBL_TRADE_DATE, HKSBL_INSNBR, HKSBL_COUNTERPARTY) SBL
	GROUP BY HKSBL_TRADE_DATE, HKSBL_INSNBR) SBL
ON SBL.HKSBL_TRADE_DATE = HKAVL_DATE
AND SBL.HKSBL_INSNBR = RIC.INSALA_INSTR_INSNBR
LEFT JOIN (
	SELECT HKOHD_DATE, HKOHD_INSNBR, SUM(HOLD_TOTAL) AS HOLD_TOTAL
	FROM (
	    SELECT HKOHD_DATE, HKOHD_INSNBR, HKOHD_COUNTERPARTY, HOLD_TOTAL + ISNULL(SBL_TOTAL, 0)¡@ AS HOLD_TOTAL
	    FROM (
	    	SELECT HKOHD_DATE, HKOHD_INSNBR, HKOHD_COUNTERPARTY, SUM(HKOHD_QUANTITY) AS HOLD_TOTAL
	    	FROM WAFT.dbo.HK_SBL_HOLD
	    	WHERE HKOHD_DATE = @PROCESS_DATE
	    	AND HKOHD_INSNBR = @INSTR_INSNBR
	    	GROUP BY HKOHD_DATE, HKOHD_INSNBR, HKOHD_COUNTERPARTY) HOLD
	    LEFT JOIN (
	    		SELECT HKSBL_TRADE_DATE, HKSBL_INSNBR, HKSBL_COUNTERPARTY, SUM(IIF(HKSBL_DIRECTION ='BORROW', HKSBL_QUANTITY,0)) - SUM(IIF(HKSBL_DIRECTION ='LEND', HKSBL_QUANTITY,0)) AS SBL_TOTAL
	    		FROM WAFT.dbo.HK_SBL_SBL
	    		WHERE HKSBL_TRADE_DATE = @PROCESS_DATE
	    	    AND HKSBL_INSNBR = @INSTR_INSNBR
	    		AND HKSBL_VER = 1
	    		GROUP BY HKSBL_TRADE_DATE, HKSBL_INSNBR, HKSBL_COUNTERPARTY) SBL
	    ON HOLD.HKOHD_COUNTERPARTY = SBL.HKSBL_COUNTERPARTY) AS HOLD
	GROUP BY HKOHD_DATE, HKOHD_INSNBR) HOLD
ON HOLD.HKOHD_DATE = HKAVL_DATE
AND HOLD.HKOHD_INSNBR = RIC.INSALA_INSTR_INSNBR
WHERE HKAVL_DATE = @PROCESS_DATE
AND RIC.INSALA_INSTR_INSNBR = @INSTR_INSNBR
)
 
SELECT
	HKAVL_DATE,
	INSALA_INSTR_INSNBR,
	INSALA_CODE,
	ISNULL(ROUND(HKAVL_MARGIN_AC_BALANCE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS HKAVL_MARGIN_AC_BALANCE,
	ISNULL(ROUND(HKAVL_SHORT_SELLING_AC_BALANCE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS SHORT_SELLING_AC_BALANCE,
	ISNULL(ROUND(ACTUAL_AVAILABLE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS ACTUAL_AVAILABLE,
	ISNULL(SBLRATE.HKDSR_SBL_RATE_1, 0) AS SBL_RATE,--30DAY
	ISNULL(ROUND(SBL_TOTAL * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS SBL_TOTAL,
	ISNULL(ROUND(HOLD_TOTAL * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS HOLD_TOTAL,
	ISNULL(ROUND(REMAINING_BALANCE * ROUND(PX.HISPRS_CLOSE * EX.HISPRS_CLOSE, 2), 2), 0) AS REMAINING_BALANCE	
FROM POSITION
LEFT JOIN WARP.dbo.HISPRICE PX
ON PX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND PX.HISPRS_INSTR_INSNBR = POSITION.INSALA_INSTR_INSNBR
AND PX.HISPRS_TYPE = 'CLOSE_MARKET'
LEFT JOIN WARP.dbo.HISPRICE EX
ON EX.HISPRS_DATE = EDAISYS.dbo.ADDDAYS(@PROCESS_DATE, 'HongKong', -1)
AND EX.HISPRS_CURRENCY_INSNBR = 11
AND EX.HISPRS_INSTR_INSNBR = 20
LEFT JOIN EXTSRC.dbo.HK_SBL_DAILY_SBL_RATE SBLRATE
ON SBLRATE.HKDSR_TICKER + ' EQUITY' = POSITION.INSALA_CODE
AND HKDSR_DATE = CONVERT(NUMERIC(10,0),CONVERT(VARCHAR, GETDATE(),112))
UNION ALL
SELECT
    HKAVL_DATE,
	INSALA_INSTR_INSNBR,
	INSALA_CODE,
	ISNULL(HKAVL_MARGIN_AC_BALANCE, 0) AS HKAVL_MARGIN_AC_BALANCE,
	ISNULL(HKAVL_SHORT_SELLING_AC_BALANCE, 0) AS SHORT_SELLING_AC_BALANCE,
	ISNULL(ACTUAL_AVAILABLE, 0) AS ACTUAL_AVAILABLE,
	ISNULL(HKAVL_NO_OF_MARGIN_HOLDER, 0) AS SBL_RATE,
	ISNULL(SBL_TOTAL, 0) AS SBL_TOTAL,
	ISNULL(HOLD_TOTAL, 0) AS HOLD_TOTAL,
	ISNULL(REMAINING_BALANCE, 0) AS REMAINING_BALANCE
FROM POSITION